File64/File64/Models/Base64ResultViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace File64.Models
{
    public class Base64ResultViewModel
    {
        public String base64Code { get; set; }
    }
}

File64/File64/Models/UploadBase64ViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace File64.Models
{
    public class UploadBase64ViewModel
    {
        [Required]
        public String base64Code { get; set; }
        [Required]
        public String fileName { get; set; }
    }
}

File64/File64/Models/UploadFileViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace File64.Models
{
    public class UploadFileViewModel
    {
        [DisplayName("上傳檔案")]
        [Required]
        public HttpPostedFileBase uploadFile { get; set; }

        //public String fileName { get; set; }
    }
}

File64/File64/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace File64.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

    }
}

File64/File64/Controllers/UploadBase64Controller.cs
using File64.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace File64.Controllers
{
    public class UploadBase64Controller : Controller
    {
        // GET: UploadBase64
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetFile(UploadBase64ViewModel model)
        {
            if (ModelState.IsValid)
            {
                var contents = Convert.FromBase64String(model.base64Code);
                return File(contents, "application/pdf",model.fileName);
               
            }
            return View("Index", model);
        }
    }
}

File64/File64/Controllers/UploadFileController.cs
using File64.Models;
using File64.Service.api;
using File64.Service.impl;
using File64.Util;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace File64.Controllers
{
    public class UploadFileController : Controller
    {
        private IBase64Service service;

        public UploadFileController()
        {
            service = new Base64ServiceImpl();
        }
        // GET: UploadFile
        public ActionResult Index()
        {
            return View();
        }

        //public ActionResult Create(UploadFileViewModel model)
        //{
        //    return Content("尚未實作");
        //}
        //參考
        //http://stackoverflow.com/questions/15680629/mvc-4-razor-file-upload
        public ActionResult GetBase64(UploadFileViewModel model)
        {
            if (ModelState.IsValid)
            {
                var convertString = service.getBase64Str(model.uploadFile);
                var result = new Base64ResultViewModel() { base64Code = convertString };
                return View("Result", result);
            }
                return View("Index",model);
        }
        public ActionResult GetBase64Ajax(UploadFileViewModel model)
        {
            if (ModelState.IsValid)
            {
                var convertString = service.getBase64Str(model.uploadFile);
                var result = new Base64ResultViewModel() { base64Code = convertString };
                return Json(result);
            }
            return Json(new { msg="false"});
        }
        //text/plain
        public ActionResult GetBase64File(UploadFileViewModel model)
        {
            if (ModelState.IsValid)
            {
                var convertString = service.getBase64Str(model.uploadFile);
                var fileName = CommonUtil.getDefalutFileName() + ".txt";
                var byteData = CommonUtil.getBytes(convertString);
                return File(byteData, "text/plain", fileName);
            }
            return Json(new { msg = "false" });
        }
    }
}

File64/File64/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

File64/File64/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

File64/File64/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("應用程式名稱", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首頁", "Index", "Home")</li>
                    <li>@Html.ActionLink("關於", "About", "Home")</li>
                    <li>@Html.ActionLink("上傳檔案", "Index", "UploadFile")</li>
                    <li>@Html.ActionLink("上傳64", "Index", "UploadBase64")</li>
                </ul>
                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 應用程式</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

File64/File64/Views/UploadBase64/Index.cshtml
@model File64.Models.UploadBase64ViewModel

@{
    ViewBag.Title = "Index";
}

<h2>上傳Base64字串</h2>


@using (Html.BeginForm("GetFile", "UploadBase64", FormMethod.Post, new { enctype = "multipart/form-data", id = "dataForm" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @*<h4>UploadBase64ViewModel</h4>
        <hr />*@
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.fileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fileName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fileName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.base64Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.base64Code, new { htmlAttributes = new { @class = "form-control" } })*@
                @*@Html.TextArea("base64Code","",  new { @class = "form-control",Styles= "width:1200px;height:200px;max-width:1200px;"  })*@
                @Html.TextAreaFor(model => model.base64Code, new { @class = "form-control", style = "width:800px;height:200px;max-width:800px;" } )
                @Html.ValidationMessageFor(model => model.base64Code, "", new { @class = "text-danger" })
            </div>
        </div>

      

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="下載檔案" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

File64/File64/Views/UploadFile/Index.cshtml
@model File64.Models.UploadFileViewModel

@{
    ViewBag.Title = "View";
}

<h2>上傳檔案</h2>


@using (Html.BeginForm("GetBase64File",
                                                    "UploadFile", FormMethod.Post,
                                                    new { enctype = "multipart/form-data", id = "dataForm" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.uploadFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="uploadFile" name="uploadFile" />
                @Html.ValidationMessageFor(model => model.uploadFile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="下載txt" class="btn btn-default" />
                <input type="button" id="btnToBase64" value="顯示轉換結果" class="btn btn-default" />
                &nbsp;
                <input type="button" id="btnReset" value="清除" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div id="divResult">
    <hr />
    <span>轉換結果</span>
    <textarea style="width:1200px;height:200px;max-width:1200px;" id="textAreaResult"></textarea>
</div>
@*<div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(function () {
            //alert("jquery");
            $("#divResult").hide();
            $("#btnToBase64").on("click", clickBtnToBase64);
            $("#btnReset").on("click", clickBtnReset);
        });
        function clickBtnToBase64() {

            //var formObj = $("#dataForm");
            @*$("#dataForm").attr("action", '@Url.Content("~/UploadFile/GetBase64")');
            $("#dataForm").submit();*@
            //alert("click clickBtnToBase64");
            var formData = new FormData();
            var file = document.getElementById("uploadFile").files[0];
            formData.append("uploadFile", file);

            $.ajax({
                type: "POST",
                url: '/UploadFile/GetBase64Ajax',
                data: formData,
                dataType: 'json',
                contentType: false,
                processData: false,
                success: function (response) {
                    $("#divResult").show();
                    //alert('succes!!' + response.base64Code);
                    $("#textAreaResult").text(response.base64Code);
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    //alert("errror:" + textStatus);
                    alert("errror:" + jqXHR.responseText + ";" + textStatus + ";" + errorThrown);
                    jqXHR.responseText
                }
            });


        }

        function clickBtnReset() {
            $("#dataForm")[0].reset();
            //$("#textAreaResult").text("");
            $("#divResult").hide();
        }
    </script>
}

File64/File64/Views/UploadFile/Result.cshtml
@model File64.Models.Base64ResultViewModel

@{
    ViewBag.Title = "Result";
}

<h2>Result</h2>

<div>

    <textarea style="width:1200px;height:200px;max-width:1200px;">@Html.Raw(Model.base64Code)</textarea>


</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |*@
    @Html.ActionLink("Back to List", "Index")
</p>